#############################################################################
# Makefile for building: myMusic.app/Contents/MacOS/myMusic
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  myMusic_for_Mac.pro
# Template: app
# Command: /Users/Edward/Qt/5.9.1/clang_64/bin/qmake -o Makefile myMusic_for_Mac.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -IirrKlang-64bit-1.6.0/include -I../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.9.1/clang_64/mkspecs/macx-clang -F/Users/Edward/Qt/5.9.1/clang_64/lib
QMAKE         = /Users/Edward/Qt/5.9.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/Edward/Qt/5.9.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/Edward/Qt/5.9.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = myMusic1.0.0
DISTDIR = /Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/.tmp/myMusic1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/Edward/Qt/5.9.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Edward/Qt/5.9.1/clang_64/lib -LirrKlang-64bit-1.6.0/bin/macosx-gcc -lirrklang -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		musicengine.cpp \
		playlist.cpp \
		library.cpp moc_mainwindow.cpp \
		moc_musicengine.cpp \
		moc_playlist.cpp \
		moc_library.cpp
OBJECTS       = main.o \
		mainwindow.o \
		musicengine.o \
		playlist.o \
		library.o \
		moc_mainwindow.o \
		moc_musicengine.o \
		moc_playlist.o \
		moc_library.o
DIST          = ../../../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		myMusic_for_Mac.pro mainwindow.h \
		musicengine.h \
		playlist.h \
		library.h main.cpp \
		mainwindow.cpp \
		musicengine.cpp \
		playlist.cpp \
		library.cpp
QMAKE_TARGET  = myMusic
DESTDIR       = 
TARGET        = myMusic.app/Contents/MacOS/myMusic

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_musicengine.h ui_playlist.h ui_library.h $(OBJECTS)  
	@test -d myMusic.app/Contents/MacOS/ || mkdir -p myMusic.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: myMusic_for_Mac.pro ../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		myMusic_for_Mac.pro \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile myMusic_for_Mac.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.9.1/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.9.1/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.9.1/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/lex.prf:
myMusic_for_Mac.pro:
../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile myMusic_for_Mac.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

myMusic.app/Contents/PkgInfo: 
	@test -d myMusic.app/Contents || mkdir -p myMusic.app/Contents
	@$(DEL_FILE) myMusic.app/Contents/PkgInfo
	@echo "APPL????" > myMusic.app/Contents/PkgInfo
myMusic.app/Contents/Resources/empty.lproj: 
	@test -d myMusic.app/Contents/Resources || mkdir -p myMusic.app/Contents/Resources
	@touch myMusic.app/Contents/Resources/empty.lproj
	
myMusic.app/Contents/Info.plist: 
	@test -d myMusic.app/Contents || mkdir -p myMusic.app/Contents
	@$(DEL_FILE) myMusic.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.edwardchau.myMusic,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,myMusic,g" -e "s,@LIBRARY@,myMusic,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.9.1/clang_64/mkspecs/macx-clang/Info.plist.app >myMusic.app/Contents/Info.plist
myMusic.app/Contents/MacOS/libirrklang.dylib: /Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/bin/macosx-gcc/libirrklang.dylib
	@test -d myMusic.app/Contents/MacOS || mkdir -p myMusic.app/Contents/MacOS
	@$(DEL_FILE) myMusic.app/Contents/MacOS/libirrklang.dylib
	@$(COPY_FILE) /Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/bin/macosx-gcc/libirrklang.dylib myMusic.app/Contents/MacOS/libirrklang.dylib
myMusic.app/Contents/MacOS/ikpFLAC.dylib: /Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/bin/macosx-gcc/ikpFLAC.dylib
	@test -d myMusic.app/Contents/MacOS || mkdir -p myMusic.app/Contents/MacOS
	@$(DEL_FILE) myMusic.app/Contents/MacOS/ikpFLAC.dylib
	@$(COPY_FILE) /Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/bin/macosx-gcc/ikpFLAC.dylib myMusic.app/Contents/MacOS/ikpFLAC.dylib
myMusic.app/Contents/MacOS/ikpMP3.dylib: /Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/bin/macosx-gcc/ikpMP3.dylib
	@test -d myMusic.app/Contents/MacOS || mkdir -p myMusic.app/Contents/MacOS
	@$(DEL_FILE) myMusic.app/Contents/MacOS/ikpMP3.dylib
	@$(COPY_FILE) /Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/bin/macosx-gcc/ikpMP3.dylib myMusic.app/Contents/MacOS/ikpMP3.dylib

all: Makefile \
		myMusic.app/Contents/PkgInfo \
		myMusic.app/Contents/Resources/empty.lproj \
		myMusic.app/Contents/Info.plist \
		myMusic.app/Contents/MacOS/libirrklang.dylib \
		myMusic.app/Contents/MacOS/ikpFLAC.dylib \
		myMusic.app/Contents/MacOS/ikpMP3.dylib $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h musicengine.h playlist.h library.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp musicengine.cpp playlist.cpp library.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui musicengine.ui playlist.ui library.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r myMusic.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_musicengine.cpp moc_playlist.cpp moc_library.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_musicengine.cpp moc_playlist.cpp moc_library.cpp
moc_mainwindow.cpp: ../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		musicengine.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		irrKlang-64bit-1.6.0/include/irrKlang.h \
		irrKlang-64bit-1.6.0/include/ik_irrKlangTypes.h \
		irrKlang-64bit-1.6.0/include/ik_vec3d.h \
		irrKlang-64bit-1.6.0/include/ik_IRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_IVirtualRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundOutputDrivers.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundEngineOptions.h \
		irrKlang-64bit-1.6.0/include/ik_EStreamModes.h \
		irrKlang-64bit-1.6.0/include/ik_SAudioStreamFormat.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEngine.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundSource.h \
		irrKlang-64bit-1.6.0/include/ik_ISound.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEffectControl.h \
		irrKlang-64bit-1.6.0/include/ik_IFileFactory.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundMixedOutputReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStream.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStreamLoader.h \
		irrKlang-64bit-1.6.0/include/ik_IFileReader.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundStopEventReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundDeviceList.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioRecorder.h \
		playlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		library.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMap \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QList \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		ui_library.h \
		mainwindow.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/Edward/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/Edward/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang -I/Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/include -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/Edward/Qt/5.9.1/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_musicengine.cpp: ../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		irrKlang-64bit-1.6.0/include/irrKlang.h \
		irrKlang-64bit-1.6.0/include/ik_irrKlangTypes.h \
		irrKlang-64bit-1.6.0/include/ik_vec3d.h \
		irrKlang-64bit-1.6.0/include/ik_IRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_IVirtualRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundOutputDrivers.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundEngineOptions.h \
		irrKlang-64bit-1.6.0/include/ik_EStreamModes.h \
		irrKlang-64bit-1.6.0/include/ik_SAudioStreamFormat.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEngine.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundSource.h \
		irrKlang-64bit-1.6.0/include/ik_ISound.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEffectControl.h \
		irrKlang-64bit-1.6.0/include/ik_IFileFactory.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundMixedOutputReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStream.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStreamLoader.h \
		irrKlang-64bit-1.6.0/include/ik_IFileReader.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundStopEventReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundDeviceList.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioRecorder.h \
		musicengine.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/Edward/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/Edward/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang -I/Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/include -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/Edward/Qt/5.9.1/clang_64/lib musicengine.h -o moc_musicengine.cpp

moc_playlist.cpp: ../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		musicengine.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		irrKlang-64bit-1.6.0/include/irrKlang.h \
		irrKlang-64bit-1.6.0/include/ik_irrKlangTypes.h \
		irrKlang-64bit-1.6.0/include/ik_vec3d.h \
		irrKlang-64bit-1.6.0/include/ik_IRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_IVirtualRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundOutputDrivers.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundEngineOptions.h \
		irrKlang-64bit-1.6.0/include/ik_EStreamModes.h \
		irrKlang-64bit-1.6.0/include/ik_SAudioStreamFormat.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEngine.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundSource.h \
		irrKlang-64bit-1.6.0/include/ik_ISound.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEffectControl.h \
		irrKlang-64bit-1.6.0/include/ik_IFileFactory.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundMixedOutputReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStream.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStreamLoader.h \
		irrKlang-64bit-1.6.0/include/ik_IFileReader.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundStopEventReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundDeviceList.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioRecorder.h \
		playlist.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/Edward/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/Edward/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang -I/Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/include -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/Edward/Qt/5.9.1/clang_64/lib playlist.h -o moc_playlist.cpp

moc_library.cpp: ../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMap \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QList \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		ui_library.h \
		library.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/Edward/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/Edward/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang -I/Users/Edward/Desktop/C++/myMusic_for_Mac_with_irrklang/irrKlang-64bit-1.6.0/include -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/Edward/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/Edward/Qt/5.9.1/clang_64/lib library.h -o moc_library.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_musicengine.h ui_playlist.h ui_library.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_musicengine.h ui_playlist.h ui_library.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/5.9.1/clang_64/bin/uic
	/Users/Edward/Qt/5.9.1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_musicengine.h: musicengine.ui \
		../../../Qt/5.9.1/clang_64/bin/uic
	/Users/Edward/Qt/5.9.1/clang_64/bin/uic musicengine.ui -o ui_musicengine.h

ui_playlist.h: playlist.ui \
		../../../Qt/5.9.1/clang_64/bin/uic
	/Users/Edward/Qt/5.9.1/clang_64/bin/uic playlist.ui -o ui_playlist.h

ui_library.h: library.ui \
		../../../Qt/5.9.1/clang_64/bin/uic
	/Users/Edward/Qt/5.9.1/clang_64/bin/uic library.ui -o ui_library.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		musicengine.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		irrKlang-64bit-1.6.0/include/irrKlang.h \
		irrKlang-64bit-1.6.0/include/ik_irrKlangTypes.h \
		irrKlang-64bit-1.6.0/include/ik_vec3d.h \
		irrKlang-64bit-1.6.0/include/ik_IRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_IVirtualRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundOutputDrivers.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundEngineOptions.h \
		irrKlang-64bit-1.6.0/include/ik_EStreamModes.h \
		irrKlang-64bit-1.6.0/include/ik_SAudioStreamFormat.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEngine.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundSource.h \
		irrKlang-64bit-1.6.0/include/ik_ISound.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEffectControl.h \
		irrKlang-64bit-1.6.0/include/ik_IFileFactory.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundMixedOutputReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStream.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStreamLoader.h \
		irrKlang-64bit-1.6.0/include/ik_IFileReader.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundStopEventReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundDeviceList.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioRecorder.h \
		playlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		library.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMap \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QList \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		ui_library.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QRect \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		musicengine.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		irrKlang-64bit-1.6.0/include/irrKlang.h \
		irrKlang-64bit-1.6.0/include/ik_irrKlangTypes.h \
		irrKlang-64bit-1.6.0/include/ik_vec3d.h \
		irrKlang-64bit-1.6.0/include/ik_IRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_IVirtualRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundOutputDrivers.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundEngineOptions.h \
		irrKlang-64bit-1.6.0/include/ik_EStreamModes.h \
		irrKlang-64bit-1.6.0/include/ik_SAudioStreamFormat.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEngine.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundSource.h \
		irrKlang-64bit-1.6.0/include/ik_ISound.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEffectControl.h \
		irrKlang-64bit-1.6.0/include/ik_IFileFactory.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundMixedOutputReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStream.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStreamLoader.h \
		irrKlang-64bit-1.6.0/include/ik_IFileReader.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundStopEventReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundDeviceList.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioRecorder.h \
		playlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		library.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMap \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QList \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		ui_library.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

musicengine.o: musicengine.cpp musicengine.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		irrKlang-64bit-1.6.0/include/irrKlang.h \
		irrKlang-64bit-1.6.0/include/ik_irrKlangTypes.h \
		irrKlang-64bit-1.6.0/include/ik_vec3d.h \
		irrKlang-64bit-1.6.0/include/ik_IRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_IVirtualRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundOutputDrivers.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundEngineOptions.h \
		irrKlang-64bit-1.6.0/include/ik_EStreamModes.h \
		irrKlang-64bit-1.6.0/include/ik_SAudioStreamFormat.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEngine.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundSource.h \
		irrKlang-64bit-1.6.0/include/ik_ISound.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEffectControl.h \
		irrKlang-64bit-1.6.0/include/ik_IFileFactory.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundMixedOutputReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStream.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStreamLoader.h \
		irrKlang-64bit-1.6.0/include/ik_IFileReader.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundStopEventReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundDeviceList.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioRecorder.h \
		ui_musicengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o musicengine.o musicengine.cpp

playlist.o: playlist.cpp playlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		musicengine.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		irrKlang-64bit-1.6.0/include/irrKlang.h \
		irrKlang-64bit-1.6.0/include/ik_irrKlangTypes.h \
		irrKlang-64bit-1.6.0/include/ik_vec3d.h \
		irrKlang-64bit-1.6.0/include/ik_IRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_IVirtualRefCounted.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundOutputDrivers.h \
		irrKlang-64bit-1.6.0/include/ik_ESoundEngineOptions.h \
		irrKlang-64bit-1.6.0/include/ik_EStreamModes.h \
		irrKlang-64bit-1.6.0/include/ik_SAudioStreamFormat.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEngine.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundSource.h \
		irrKlang-64bit-1.6.0/include/ik_ISound.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundEffectControl.h \
		irrKlang-64bit-1.6.0/include/ik_IFileFactory.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundMixedOutputReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStream.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioStreamLoader.h \
		irrKlang-64bit-1.6.0/include/ik_IFileReader.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundStopEventReceiver.h \
		irrKlang-64bit-1.6.0/include/ik_ISoundDeviceList.h \
		irrKlang-64bit-1.6.0/include/ik_IAudioRecorder.h \
		ui_playlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QDropEvent \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QStandardItem \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playlist.o playlist.cpp

library.o: library.cpp library.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QMap \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QList \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		ui_library.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o library.o library.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_musicengine.o: moc_musicengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_musicengine.o moc_musicengine.cpp

moc_playlist.o: moc_playlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playlist.o moc_playlist.cpp

moc_library.o: moc_library.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_library.o moc_library.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

